// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMiWZzVj0I0_yIK5hK-j09dIIdq1Ql4a4',
    appId: '1:1054021400249:web:6d6053dcd4fba7debdcd68',
    messagingSenderId: '1054021400249',
    projectId: 'final-2004',
    authDomain: 'final-2004.firebaseapp.com',
    storageBucket: 'final-2004.firebasestorage.app',
    measurementId: 'G-3H2PLYQB8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ZiR8QMDjHoaCgVSdsi_oLCIR9pbL3uk',
    appId: '1:1054021400249:android:fcf748960e5aeb99bdcd68',
    messagingSenderId: '1054021400249',
    projectId: 'final-2004',
    storageBucket: 'final-2004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByXkM9S7w-zwMP3fWTSsqgQ2Zu077Oxl4',
    appId: '1:1054021400249:ios:579f22d37b522fdbbdcd68',
    messagingSenderId: '1054021400249',
    projectId: 'final-2004',
    storageBucket: 'final-2004.firebasestorage.app',
    iosBundleId: 'com.example.treeClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByXkM9S7w-zwMP3fWTSsqgQ2Zu077Oxl4',
    appId: '1:1054021400249:ios:579f22d37b522fdbbdcd68',
    messagingSenderId: '1054021400249',
    projectId: 'final-2004',
    storageBucket: 'final-2004.firebasestorage.app',
    iosBundleId: 'com.example.treeClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMiWZzVj0I0_yIK5hK-j09dIIdq1Ql4a4',
    appId: '1:1054021400249:web:0caefc7767a4e8e8bdcd68',
    messagingSenderId: '1054021400249',
    projectId: 'final-2004',
    authDomain: 'final-2004.firebaseapp.com',
    storageBucket: 'final-2004.firebasestorage.app',
    measurementId: 'G-QJMM731Y5K',
  );
}
